In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df_ipl = pd.read_csv('data/ipl.csv')

In [98]:
df_ipl.shape

(76014, 15)

In [3]:
df_ipl.head(20)

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222
5,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.5,2,0,0,0,222
6,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,3,0,0.6,3,0,0,0,222
7,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,3,0,1.1,3,0,0,0,222
8,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,7,0,1.2,7,0,4,0,222
9,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,11,0,1.3,11,0,8,0,222
10,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,17,0,1.4,17,0,14,0,222
11,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,21,0,1.5,21,0,18,0,222
12,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Z Khan,21,0,1.6,21,0,18,0,222
13,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,21,0,2.1,21,0,18,0,222
14,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,21,0,2.2,21,0,18,0,222
15,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,22,0,2.3,22,0,18,0,222
16,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,26,0,2.4,26,0,22,0,222
17,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,27,0,2.5,27,0,23,0,222
18,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,27,0,2.6,27,0,23,0,222
19,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,AA Noffke,32,0,3.0,32,0,23,0,222

In [88]:
df_ipl.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33946 entries, 32 to 75888
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            33946 non-null  datetime64[ns]
 1   venue           33946 non-null  object
 2   bat_team        33946 non-null  object
 3   bowl_team       33946 non-null  object
 4   runs            33946 non-null  int64
 5   wickets         33946 non-null  int64
 6   overs           33946 non-null  float64
 7   runs_last_5     33946 non-null  int64
 8   wickets_last_5  33946 non-null  int64
 9   total           33946 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 2.8+ MB

In [12]:
df_ipl.columns

Index(['mid', 'date', 'venue', 'bat_team', 'bowl_team', 'batsman', 'bowler',
       'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5', 'striker',
       'non-striker', 'total'],
      dtype='object')

In [99]:
df_ipl.drop(['mid','batsman', 'bowler', 'striker', 'non-striker'],axis = 1, inplace = True)

In [4]:
df_ipl.tail()

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
76009,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,121,7,19.2,40,0,40,12,129
76010,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,127,7,19.3,46,0,46,12,129
76011,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,128,7,19.4,47,0,47,12,129
76012,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,MG Johnson,DT Christian,129,7,19.5,48,0,47,13,129
76013,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,129,8,19.6,47,1,47,13,129

In [28]:
df_ipl['venue'].value_counts()

M Chinnaswamy Stadium                                   7443
Feroz Shah Kotla                                        7068
Eden Gardens                                            7049
Wankhede Stadium                                        7048
MA Chidambaram Stadium, Chepauk                         5972
Rajiv Gandhi International Stadium, Uppal               5827
Punjab Cricket Association Stadium, Mohali              4247
Sawai Mansingh Stadium                                  4110
Dr DY Patil Sports Academy                              2088
Subrata Roy Sahara Stadium                              2086
Maharashtra Cricket Association Stadium                 1843
Kingsmead                                               1731
Sardar Patel Stadium, Motera                            1484
Brabourne Stadium                                       1380
SuperSport Park                                         1377
Punjab Cricket Association IS Bindra Stadium, Mohali    1342
Saurashtra Cricket Association Stadium                  1229
Himachal Pradesh Cricket Association Stadium            1115
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     1113
New Wanderers Stadium                                    995
St George's Park                                         870
Dubai International Cricket Stadium                      868
Barabati Stadium                                         856
JSCA International Stadium Complex                       837
Sheikh Zayed Stadium                                     836
Sharjah Cricket Stadium                                  744
Shaheed Veer Narayan Singh International Stadium         742
Newlands                                                 737
Holkar Cricket Stadium                                   617
Nehru Stadium                                            499
Green Park                                               492
Buffalo Park                                             380
Vidarbha Cricket Association Stadium, Jamtha             370
De Beers Diamond Oval                                    368
OUTsurance Oval                                          251
Name: venue, dtype: int64

In [100]:
col = df_ipl['venue'].value_counts()<4000

In [101]:
df = pd.DataFrame(col,columns = ['venue'])
df['sta'] = df.index

In [102]:
df

,venue,sta
M Chinnaswamy Stadium,False,M Chinnaswamy Stadium
Feroz Shah Kotla,False,Feroz Shah Kotla
Eden Gardens,False,Eden Gardens
Wankhede Stadium,False,Wankhede Stadium
"MA Chidambaram Stadium, Chepauk",False,"MA Chidambaram Stadium, Chepauk"
"Rajiv Gandhi International Stadium, Uppal",False,"Rajiv Gandhi International Stadium, Uppal"
"Punjab Cricket Association Stadium, Mohali",False,"Punjab Cricket Association Stadium, Mohali"
Sawai Mansingh Stadium,False,Sawai Mansingh Stadium
Dr DY Patil Sports Academy,True,Dr DY Patil Sports Academy
Subrata Roy Sahara Stadium,True,Subrata Roy Sahara Stadium
Maharashtra Cricket Association Stadium,True,Maharashtra Cricket Association Stadium
Kingsmead,True,Kingsmead
"Sardar Patel Stadium, Motera",True,"Sardar Patel Stadium, Motera"
Brabourne Stadium,True,Brabourne Stadium
SuperSport Park,True,SuperSport Park
"Punjab Cricket Association IS Bindra Stadium, Mohali",True,"Punjab Cricket Association IS Bindra Stadium, ..."
Saurashtra Cricket Association Stadium,True,Saurashtra Cricket Association Stadium
Himachal Pradesh Cricket Association Stadium,True,Himachal Pradesh Cricket Association Stadium
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium,True,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
New Wanderers Stadium,True,New Wanderers Stadium
St George's Park,True,St George's Park
Dubai International Cricket Stadium,True,Dubai International Cricket Stadium
Barabati Stadium,True,Barabati Stadium
JSCA International Stadium Complex,True,JSCA International Stadium Complex
Sheikh Zayed Stadium,True,Sheikh Zayed Stadium
Sharjah Cricket Stadium,True,Sharjah Cricket Stadium
Shaheed Veer Narayan Singh International Stadium,True,Shaheed Veer Narayan Singh International Stadium
Newlands,True,Newlands
Holkar Cricket Stadium,True,Holkar Cricket Stadium
Nehru Stadium,True,Nehru Stadium
Green Park,True,Green Park
Buffalo Park,True,Buffalo Park
"Vidarbha Cricket Association Stadium, Jamtha",True,"Vidarbha Cricket Association Stadium, Jamtha"
De Beers Diamond Oval,True,De Beers Diamond Oval
OUTsurance Oval,True,OUTsurance Oval

In [103]:
for i in range(35):
    if(df['venue'][i]):
        df_ipl['venue'].replace(df['sta'][i],'Other',inplace = True)

In [77]:
df_ipl['bat_team'].value_counts()

Mumbai Indians                 10213
Kings XI Punjab                 9219
Chennai Super Kings             9142
Royal Challengers Bangalore     8331
Kolkata Knight Riders           8033
Delhi Capitals                  7152
Rajasthan Royals                6643
Deccan Chargers                 5280
Sunrisers Hyderabad             5216
Pune Warriors                   2448
Gujarat Lions                   1726
Rising Pune Supergiant           994
Kochi Tuskers Kerala             876
Rising Pune Supergiants          741
Name: bat_team, dtype: int64

In [104]:
df_ipl['bat_team'].replace('Delhi Daredevils','Delhi Capitals',inplace = True)

In [105]:
df_ipl['bowl_team'].replace('Delhi Daredevils','Delhi Capitals',inplace = True)

In [106]:
consistent_teams = ['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
                    'Mumbai Indians', 'Kings XI Punjab', 'Royal Challengers Bangalore',
                    'Delhi Capitals', 'Sunrisers Hyderabad']

In [107]:
df_ipl = df_ipl[(df_ipl['bat_team'].isin(consistent_teams)) & (df_ipl['bowl_team'].isin(consistent_teams))]

In [108]:
df_ipl.shape

(53811, 10)

In [109]:
df_ipl = df_ipl[df_ipl['overs']>=5.0]

In [110]:
from datetime import datetime
df_ipl['date'] = df_ipl['date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d'))

In [111]:
df = pd.get_dummies(data=df_ipl, columns=['venue','bat_team', 'bowl_team'],drop_first =True)

In [112]:
df.shape

(40108, 29)

In [114]:
df

,date,runs,wickets,overs,runs_last_5,wickets_last_5,total,venue_Feroz Shah Kotla,venue_M Chinnaswamy Stadium,"venue_MA Chidambaram Stadium, Chepauk",...,bat_team_Rajasthan Royals,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Delhi Capitals,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad
32,2008-04-18,61,0,5.1,59,0,222,0,1,0,...,0,0,0,0,0,0,0,0,1,0
33,2008-04-18,61,1,5.2,59,1,222,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34,2008-04-18,61,1,5.3,59,1,222,0,1,0,...,0,0,0,0,0,0,0,0,1,0
35,2008-04-18,61,1,5.4,59,1,222,0,1,0,...,0,0,0,0,0,0,0,0,1,0
36,2008-04-18,61,1,5.5,58,1,222,0,1,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75884,2017-05-19,106,9,18.1,29,4,107,0,1,0,...,0,0,0,0,0,0,1,0,0,0
75885,2017-05-19,107,9,18.2,29,4,107,0,1,0,...,0,0,0,0,0,0,1,0,0,0
75886,2017-05-19,107,9,18.3,28,4,107,0,1,0,...,0,0,0,0,0,0,1,0,0,0
75887,2017-05-19,107,9,18.4,24,4,107,0,1,0,...,0,0,0,0,0,0,1,0,0,0
75888,2017-05-19,107,10,18.5,23,5,107,0,1,0,...,0,0,0,0,0,0,1,0,0,0

In [161]:
X_train = df.drop('total',axis = 1)[df['date'].dt.year<=2016]
X_test = df.drop('total',axis = 1)[df['date'].dt.year>2016]

In [162]:
y_test.shape

(2778, 1)

In [163]:
y_train = df[df['date'].dt.year<=2016]['total'].values
y_test = df[df['date'].dt.year>2016]['total'].values

In [164]:
X_train.drop(['date'],axis = 1,inplace =True)
X_test.drop(['date'],axis = 1,inplace =True)

In [165]:
from sklearn.preprocessing import StandardScaler

In [166]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [152]:
y_train=scaler.fit_transform(y_train.reshape(-1,1))
y_test=scaler.transform(y_test.reshape(-1,1))

In [167]:
y_train

array([222, 222, 222, ..., 208, 208, 208], dtype=int64)

In [168]:
from sklearn.linear_model import LinearRegression

In [156]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [177]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

ridge=Ridge()
parameters={'alpha':[1e-20,1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40]}
ridge_regressor=GridSearchCV(ridge,parameters,scoring='neg_mean_squared_error',cv=5)
ridge_regressor.fit(X_train,y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=False, random_state=None,
                             solver='auto', tol=0.001),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': [1e-20, 1e-15, 1e-10, 1e-08, 0.001, 0.01, 1,
                                   5, 10, 20, 30, 35, 40]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=0)

In [178]:
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 1e-20}
-333.2875671926451

In [179]:
prediction=ridge_regressor.predict(X_test)

In [180]:
from sklearn import metrics
import numpy as np
print('MAE:', metrics.mean_absolute_error(y_test, prediction))
print('MSE:', metrics.mean_squared_error(y_test, prediction))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, prediction)))

MAE: 12.29686446355247
MSE: 260.7406749438093
RMSE: 16.147466517810443

In [182]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

lasso=Lasso()
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40]}
lasso_regressor=GridSearchCV(lasso,parameters,scoring='neg_mean_squared_error',cv=5)

lasso_regressor.fit(X_train,y_train)
print(lasso_regressor.best_params_)
print(lasso_regressor.best_score_)

G:\Anaconda\envs\tensorflow2\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3011142.0418157987, tolerance: 2529.9556965945626
  positive)
G:\Anaconda\envs\tensorflow2\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 563988.8983577834, tolerance: 2547.0380710286627
  positive)
G:\Anaconda\envs\tensorflow2\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1087526.4148495635, tolerance: 2667.8126904366463
  positive)
G:\Anaconda\envs\tensorflow2\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2317839.942116822, tolerance: 2712.348891397669
  positive)
G:\Anaconda\envs\tensorflow2\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1830298.0762726525, tolerance: 2646.143766019284
  positive)

{'alpha': 0.01}
-332.84575574628707

In [183]:
prediction=lasso_regressor.predict(X_test)

print('MAE:', metrics.mean_absolute_error(y_test, prediction))
print('MSE:', metrics.mean_squared_error(y_test, prediction))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, prediction)))

MAE: 12.303376216872175
MSE: 261.07481326056364
RMSE: 16.157809667791103

In [184]:
def custom_accuracy(y_test,y_pred,thresold):
    right = 0

    l = len(y_pred)
    for i in range(0,l):
        if(abs(y_pred[i]-y_test[i]) <= thresold):
            right += 1
    return ((right/l)*100)

In [188]:
score = lasso_regressor.score(X_test,y_test)
print("R square value:" , score)
print("Custom accuracy:" , custom_accuracy(y_test,prediction,20))

R square value: -261.07481326056364
Custom accuracy: 79.6976241900648